export {default as Cinflex } from './Cinflex/Cinflex'
export {default as Signup} from './Signup/Signup'
export {default as Login} from './Login/Login'
export {default as Player} from './Player/Player'
export  {default as Movies} from './Movies/Movies'
export  {default as Tvshows} from './Tvshows/Tvshows'