export {default as Header} from './Header/Header'
export {default as Backgroundimage } from './Backgroundimage/Backgroundimage'
export {default as Navbar} from './Navbar/Navbar'
export  {default as CardSlider} from './CardSlider/CardSlider'
export  {default as Card} from './Card/Card'
export {default as Slider} from './Slider/Slider'
export {default as NotAvqailable} from './NotAvailable/NotAvailable'
export  {default as Selectgenre} from './Selectgenre/Selectgenre'