export {default as Header} from './Header/Header'
export {default as Backgroundimage } from './Backgroundimage/Backgroundimage'
export {default as Navbar} from './Navbar/Navbar'
export  {default as CardSlider} from './CardSlider/CardSlider'
export  {default as Card} from './Card/Card'
export {default as Slider} from './Slider/Slider'